import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

export default function Terms() {
  return (
    <div className="bg-slate-50 font-sans text-slate-800 min-h-screen">
      {/* Header */}
      <header className="bg-slate-900 text-white py-16">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <h1 className="text-4xl font-extrabold mb-4">Terms of Use</h1>
          <p className="text-slate-400">Last Updated: October 26, 2026</p>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-white rounded-2xl shadow-sm p-8 md:p-12 space-y-8 leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">1. Agreement to Terms</h2>
            <p>
              These Terms of Use constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you") and <strong>Demandio</strong> ("we", "us", or "our"), concerning your access to and use of the demandio.cloud website and our associated tools (Subsidy Finder, VSME Reporter).
            </p>
            <p className="mt-4">
              By accessing the Site, you confirm that you have read, understood, and agreed to be bound by all of these Terms of Use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">2. Intellectual Property Rights</h2>
            <p>
              Unless otherwise indicated, the Site and its proprietary software, source code, databases, functionality, website designs, audio, video, text, photographs, and graphics on the Site (collectively, the "Content") are owned or controlled by us and are protected by copyright and trademark laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">3. Use of Services & Tools</h2>
            <p>
              <strong>Subsidy Finder:</strong> The results provided by our Subsidy Finder are estimates based on the information you provide and general regulatory criteria. They do <strong>not</strong> constitute a guarantee of funding or eligibility. Actual subsidy approval is subject to the discretion of the relevant government bodies (e.g., RVO).
            </p>
            <p className="mt-4">
              <strong>VSME Reporter:</strong> Reports generated are for informational and internal use purposes. While we strive for alignment with current standards (VSME), we do not guarantee compliance with evolving regulations without professional auditing.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">4. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, Demandio shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>Your access to or use of or inability to access or use the Site;</li>
              <li>Any conduct or content of any third party on the Site;</li>
              <li>Any reliance placed on the completeness, accuracy, or existence of any information or results generated by our tools.</li>
            </ul>
            <p className="mt-4 bg-yellow-50 p-4 rounded-lg border border-yellow-100 text-yellow-800 text-sm">
              <strong>Note:</strong> We do not provide financial or legal advice. You should consult with a qualified professional before making financial decisions based on our tool outputs.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">5. User Data</h2>
            <p>
              We care about your data privacy and security. Please review our <Link to="/privacy" className="text-blue-600 hover:underline">Privacy Policy</Link>. By using the Site, you agree to be bound by our Privacy Policy, which is incorporated into these Terms of Use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">6. Governing Law</h2>
            <p>
              These Terms shall be governed by and defined following the laws of <strong>The Netherlands</strong>. Demandio and yourself irrevocably consent that the courts of The Netherlands shall have exclusive jurisdiction to resolve any dispute which may arise in connection with these terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">7. Contact Us</h2>
            <p>
              In order to resolve a complaint regarding the Site or to receive further information regarding use of the Site, please contact us at:
            </p>
            <address className="mt-4 not-italic">
              <strong>Demandio</strong><br />
              Fluwelen Burgwal 58<br />
              2511CJ Den Haag<br />
              The Netherlands<br />
              <a href="mailto:mike@demandio.cloud" className="text-blue-600 hover:underline">mike@demandio.cloud</a>
            </address>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-slate-900 text-slate-400 py-8 text-center mt-12">
        <p>&copy; 2026 Demandio Netherlands. All rights reserved.</p>
      </footer>
    </div>
  );
}
